In [1]:
# python zip explained
l1 = [1,2,3]
l2 = [4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [2]:
# using python list
import time

size = 1_000_000_0

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(add[0:10])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
1.137357473373413


In [3]:
import numpy as np
import time

size = 1_000_000_0

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1+l2
end = time.time()

print(add[0:10])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.12484025955200195


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


# Exercises for Practice

## Create a NumPy array with values from 10 to 100 and print its shape

In [10]:
arr_p = np.arange(10,101,1)
arr_p

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
arr_p.shape

(91,)

## Compare the time taken to multiply two Python lists vs. two NumPy arrays

In [13]:
# lists
import time

# python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x*y for x,y in zip(list1,list2)]
end = time.time()
print(f"Python list multiplication time: {end-start}")

Python list multiplication time: 0.08930063247680664


In [14]:
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1*arr2
end = time.time()
print(f"Numpy multiplication time: {end-start}")

Numpy multiplication time: 0.01767587661743164


## Find the memory size of a NumPy array with 1 million elements.

In [18]:
import sys

size = 1_000_000
list1 = list(range(size))
print(f"{sys.getsizeof(list1)*len(list1)}, bytes")
#numpy_data = np.array(list1)
numpy_data = np.arange(1,1_000_000,1)
print(f"{numpy_data.nbytes}, bytes")

8000056000000, bytes
3999996, bytes
