In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5]) # 1D array
arr2 = np.array([[1,2,3],[4,5,6]]) # 2D array

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [2]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,4)) # 2x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
# 2x2 array filled with 7
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [8]:
# 4x4 identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# [1,3,5,7,9] (like range)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
# [0,1,5] (evenly spaced)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
arr = np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
# shape (2,3) 2row, 3 columns
arr.shape

(2, 3)

In [21]:
# total elements
arr.size

6

In [22]:
# Is it 2D array
arr.ndim

2

In [23]:
# Datatype int64(or int32 on Window)
arr.dtype

dtype('int32')

# Changing Data types

In [24]:
# explicit type
arr = np.array([1,2,3],dtype=np.float32)

In [25]:
arr

array([1., 2., 3.], dtype=float32)

In [26]:
# convert float to int
arr_int = arr.astype(np.int32)
arr_int

array([1, 2, 3])

# 4. Reshaping and Flattening Arrays

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [28]:
reshaped = arr.reshape((3,2))
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# 2D to 1D
flattened = arr.flatten()
flattened

array([1, 2, 3, 4, 5, 6])