# Indexing

In [2]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0]) #10
print(arr[-1])# 40

10
40


# Slicing (extracting Parts of an Array)

In [4]:
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print([arr[::2]])

[20 30 40]
[10 20 30]
[array([10, 30, 50])]


## Slicing returns a view, not a copy! Changes affect the original array

In [8]:
arr

array([10, 20, 30, 40, 50])

In [9]:
sliced = arr[1:4]

In [10]:
sliced

array([20, 30, 40])

In [11]:
sliced[0] = 999

In [12]:
sliced

array([999,  30,  40])

In [13]:
print(arr)

[ 10 999  30  40  50]


use .copy() if you need an independent copy

In [15]:
newsliced = arr[1:4].copy()

In [16]:
newsliced

array([999,  30,  40])

In [17]:
arr

array([ 10, 999,  30,  40,  50])

In [18]:
newsliced[0]=333

In [19]:
newsliced

array([333,  30,  40])

In [20]:
arr

array([ 10, 999,  30,  40,  50])

# Fancy Indexing (Select Multiple elements)

In [22]:
import numpy as np
arr = np.array([10,20,30,40,50])
idx = [0,2,4] 
print(arr[idx])

[10 30 50]


# Boolean Masking (Filter Data)

In [24]:
import numpy as np
arr = np.array([10,20,30,40,50])
mask = arr > 25
print(arr[mask])

[30 40 50]


# Exercises for Practice

In [4]:
#Create a 3×3 array filled with random numbers and print its shape.

import numpy as np
arr = np.random.rand(3,3)
print(arr)
print(arr.shape)

[[0.8709845  0.40552666 0.38834428]
 [0.6507372  0.75373592 0.19288823]
 [0.23876962 0.66994696 0.63847467]]
(3, 3)


In [7]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers

arr = np.array([1.1,1.2,1.3])
print(arr)
print(arr.dtype)

arr_int = arr.astype(np.int32)
print(arr_int)
print(arr)
print(arr_int.dtype)

[1.1 1.2 1.3]
float64
[1 1 1]
[1.1 1.2 1.3]
int32


In [11]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
import numpy as np
arr = np.array([1,2,3,4,5,6])
idx = [1,3,5]
arr[idx]

array([2, 4, 6])

In [12]:
# Reshape a 1D array of size 9 into a 3×3 matrix
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Use boolean masking to filter numbers greater than 50 in an array
import numpy as np
arr = np.array([10,20,50,60])
arr[arr>50]

array([60])