# Understanding Axes in Numpy

In [1]:
# Axes in a 2D Array

import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# Summing along axes
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[12 15 18]
[ 6 15 24]


# 2 Indexing in Multidimnsional Arrays

In [4]:
# Accesssing an element
print(arr[1,2])

6


In [5]:
# Slicing
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


# Indexing in 3D Arrays

In [6]:
arr3D = np.array([[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]])

print(arr3D.shape)

(2, 2, 3)


In [7]:
# Accesssing elements in 3D

print(arr3D[0,1,2])

6


In [8]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


# Practical example:Selecting Data Along AxeS

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Get all rows of the first column
first_col =arr[:,0]
print(first_col)

[1 4 7]


In [11]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
# Get the first row from each "sheet" in a 3D array
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


# 5 Changing Data Along an Axis

In [13]:
# Replace all elements in column 1 with 0
arr[:,1] = 0

print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
