# Broadcasting in NumPy

## why loops are slow

In [1]:
import numpy as np
import time

arr = np.arange(1_000_000)


In [2]:
start = time.perf_counter()

result_loop=[]
for num in arr:
    result_loop.append(num**2)

end = time.perf_counter()
print(f"Loop time {end-start}")

Loop time 0.48062550000000215


# Vectorization: Fixing the Loop Problem

In [3]:
start = time.perf_counter()

result_numpy=arr**2

end = time.perf_counter()
print(f"Loop time {end-start}")

Loop time 0.0036703000000102293


## Broadcasting: Scaling Arrays without extra Memory

In [4]:
arr = np.array([1,2,3,4,5])
result = arr + 10 # broadcasting: 10 is added to all elements
print(result)

[11 12 13 14 15]


# Broadcasting with Arrays of Different Shaps

## Broadcating with Two Arrays

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

result = arr1+arr2
print(result)

[11 22 33]


## Broadcasting a 2D Array and a 1D Array

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]]) # shape 2x3
arr2 = np.array([1,2,3]) # shap 1x3
result = arr1 +arr2
print(result)

[[2 4 6]
 [5 7 9]]


# Hands-on: Applying Broadcating to Real-world Scenarios

## Normalizing Data Using Broadcasting

In [7]:
# Simulating a datast
data = np.array([
    [10,20,30],
    [15,25,35],
    [20,30,40],
    [25,35,45],
    [30,40,50]
])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean)/std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
